foreground                     #d4be98
background                     #1d2021
selection_foreground           #1d2021
selection_background           #3c3836

cursor                         #d4be98
cursor_text_color              #1d2021

url_color                      #a9b665

active_border_color            #7deae3
inactive_border_color          #504945
bell_border_color              #d8a657

wayland_titlebar_color system
macos_titlebar_color system

active_tab_foreground          #1d2021
active_tab_background          #a9b665
inactive_tab_foreground        #d4be98
inactive_tab_background        #282828
tab_bar_background             #1d2021

mark1_foreground #1d2021
mark1_background #7daea3
mark2_foreground #1d2021
mark2_background #d3869b
mark3_foreground #1d2021
mark3_background #89b482

color0 #1d2021
color8 #665c54

color1 #ea6962
color9 #ea6962

color2 #a9b665
color10 #a9b665

color3 #d8a657
color11 #d8a657

color4 #6deae3
color12 #6deae3

color5 #d3869b
color13 #d3869b

color6 #89b482
color14 #89b482

color7 #d4be98
color15 #ddc7a1
